---
- name: Install dependencies
  apt:
    name:
      - curl
      - docker.io
    state: present
    update_cache: yes

- name: Add user to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes

- name: Ensure docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes

