---
- name: Install dependencies
  apt:
    name:
      - curl
      - git
      - docker.io
    state: present
    update_cache: yes

- name: Add user to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes

- name: Install Lunarvim
  shell: |
    bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/master/utils/installer/install.sh)

- name: Reload shell
  shell: exec $SHELL

- name: Ensure docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes

